--cohort 2 
----------------------------------------------------------------------------------------------
--Create project specified formatted WRRS table
					
CALL fnc.DROP_IF_exists('SAILW1169V.WRRS_FINAL');

CREATE TABLE SAILW1169V.WRRS_FINAL
(ALF VARCHAR(20),
URINE_DATE DATE,
URINE_RESULT INTEGER,
URINE_ORG INTEGER,
TRIMETH INTEGER,
NITRO INTEGER,
AMOX INTEGER,
CO_AMOX INTEGER,
CEFALEXIN INTEGER,
GENT INTEGER,
PIVMEC INTEGER,
FOSFO INTEGER,
CIPRO INTEGER,
ESCO INTEGER,
PROV_DEPT_SITEID INTEGER);

INSERT INTO SAILW1169V.WRRS_FINAL
(SELECT ALF_PE,
		SPCM_COLLECTED_DT,
		CASE WHEN UTI_OUTCOME = 'Exclude NULL culture'
			THEN NULL
				WHEN UTI_OUTCOME = 'No microbiological evidence of UTI'
			THEN 0
				WHEN UTI_OUTCOME = 'Mixed growth'
			THEN 1
				WHEN UTI_OUTCOME = 'Heavy mixed growth'
			THEN 2
				WHEN UTI_OUTCOME = 'Possible UTI'
			THEN 3
		WHEN UTI_OUTCOME = 'Confirmed UTI'
			THEN 4
		END,
		CASE WHEN DIAG_ORGANISM = 'coliform'
			THEN 1
				WHEN DIAG_ORGANISM = 'ecoli'
			THEN 2
				WHEN DIAG_ORGANISM = 'enterococcus'
			THEN 3
				WHEN DIAG_ORGANISM = 'klebsiella'
			THEN 4
				WHEN DIAG_ORGANISM = 'proteus'
			THEN 5
				WHEN DIAG_ORGANISM = 'pseudomonas'
			THEN 6
				WHEN DIAG_ORGANISM = 'saureus'
			THEN 7
				WHEN DIAG_ORGANISM = 'staphcoagneg'
			THEN 8
				WHEN DIAG_ORGANISM = 'staphepidermidis'
			THEN 9
				WHEN DIAG_ORGANISM = 'strep'
			THEN 10
				WHEN DIAG_ORGANISM = '>1 Organism'
			THEN 11
				WHEN DIAG_ORGANISM = 'N/A'
			THEN NULL
		END,
		CASE WHEN TRIMETHOPRIM = 'Sensitive'
			THEN 0
				WHEN TRIMETHOPRIM = 'Intermediate'
			THEN 1
				WHEN TRIMETHOPRIM = 'Resistant'
			THEN 2
				WHEN TRIMETHOPRIM = 'N/A'
			THEN NULL
		END,
		CASE WHEN NITROFURANTOIN = 'Sensitive'
			THEN 0
				WHEN NITROFURANTOIN = 'Intermediate'
			THEN 1
				WHEN NITROFURANTOIN = 'Resistant'
			THEN 2
				WHEN NITROFURANTOIN = 'N/A'
			THEN NULL
		END,
		CASE WHEN AMOXICILLIN = 'Sensitive'
			THEN 0
				WHEN AMOXICILLIN = 'Intermediate'
			THEN 1
				WHEN AMOXICILLIN = 'Resistant'
			THEN 2
				WHEN AMOXICILLIN = 'N/A'
			THEN NULL
		END,
		CASE WHEN AMOXICILLIN_CLAVULANATE = 'Sensitive'
			THEN 0
				WHEN AMOXICILLIN_CLAVULANATE = 'Intermediate'
			THEN 1
				WHEN AMOXICILLIN_CLAVULANATE = 'Resistant'
			THEN 2
				WHEN AMOXICILLIN_CLAVULANATE = 'N/A'
			THEN NULL
		END,
		CASE WHEN CEPHALEXIN = 'Sensitive'
			THEN 0
				WHEN CEPHALEXIN = 'Intermediate'
			THEN 1
				WHEN CEPHALEXIN = 'Resistant'
			THEN 2
				WHEN CEPHALEXIN = 'N/A'
			THEN NULL
		END,
		CASE WHEN GENTAMICIN = 'Sensitive'
			THEN 0
				WHEN GENTAMICIN = 'Intermediate'
			THEN 1
				WHEN GENTAMICIN = 'Resistant'
			THEN 2
				WHEN GENTAMICIN = 'N/A'
			THEN NULL
		END,
		CASE WHEN PIVMECILLINAM = 'Sensitive'
			THEN 0
				WHEN PIVMECILLINAM = 'Intermediate'
			THEN 1
				WHEN PIVMECILLINAM = 'Resistant'
			THEN 2
				WHEN PIVMECILLINAM = 'N/A'
			THEN NULL
		END,
		CASE WHEN FOSFOMYCIN = 'Sensitive'
			THEN 0
				WHEN FOSFOMYCIN = 'Intermediate'
			THEN 1
				WHEN FOSFOMYCIN = 'Resistant'
			THEN 2
				WHEN FOSFOMYCIN = 'N/A'
			THEN NULL
		END,
		CASE WHEN CIPROFLOXACIN = 'Sensitive'
			THEN 0
				WHEN CIPROFLOXACIN = 'Intermediate'
			THEN 1
				WHEN CIPROFLOXACIN = 'Resistant'
			THEN 2
				WHEN CIPROFLOXACIN = 'N/A'
			THEN NULL
		END,
		ESCO,
		PROV_DEPT_SITEID
FROM SAILW1169V.COHORT_WRRS_RESULTS_AGREED);

SELECT * FROM SAILW1169V.COHORT_WRRS_RESULTS_AGREED;

-----------------------------------------------------------------------------------------------

--Cohort 2 Table 1. All WRRS results within 12 month lookback and 6 day look forward from rUTI diagnosis date

CALL FNC.DROP_IF_EXISTS('SAILW1169V.COHORT2_TABLE1_12MONTHS');

CREATE TABLE SAILW1169V.COHORT2_TABLE1_12MONTHS AS
(SELECT * FROM SAILW1169V.WRRS_FINAL)
WITH NO DATA;

INSERT INTO SAILW1169V.COHORT2_TABLE1_12MONTHS
(SELECT wrrs.*
FROM SAILW1169V.VB_COHORT1_ANALYSIS_READY AS coh
LEFT JOIN SAILW1169V.WRRS_FINAL AS wrrs
ON coh.ALF = wrrs.ALF
WHERE (wrrs.URINE_DATE BETWEEN (coh.RUTI_DIAGDATE - 1 YEAR + 1 DAY) AND (coh.RUTI_DIAGDATE + 6 DAYS))
AND wrrs.ALF IS NOT NULL);

-----------------------------------------------------------------------------------------------
--cohort 2 Table 2. WRRS results within 7 days of an acute UTI contributing to rUTI diagnosis

-- identify start dates for acute UTIs contributing to rUTI diagnosis

CALL FNC.DROP_IF_EXISTS('SAILW1169V.VB_ACUTE_UTI_IN_RUTI');

CREATE TABLE SAILW1169V.VB_ACUTE_UTI_IN_RUTI AS
(SELECT coh.ALF,
		coh.RUTI_DIAGDATE,
		uti.PREV_EVENT_STR_DT,
		uti.PREV2_EVENT_STR_DT,
		uti.TWO_EVENT_6_MNT,
		uti.THREE_EVENT_12_MNT
FROM SAILW1169V.VB_COHORT1_ANALYSIS_READY AS coh,
SAILW1169V.VB_ALL_UTI_COMB AS uti)
WITH NO DATA;

INSERT INTO SAILW1169V.VB_ACUTE_UTI_IN_RUTI
(SELECT coh.ALF,
		coh.RUTI_DIAGDATE,
		uti.PREV_EVENT_STR_DT,
		CASE WHEN uti.THREE_EVENT_12_MNT = 0 
					THEN NULL
					ELSE uti.PREV2_EVENT_STR_DT
				END AS PREV2_EVENT_STR_DT,
		uti.TWO_EVENT_6_MNT,
		uti.THREE_EVENT_12_MNT
FROM SAILW1169V.VB_COHORT1_ANALYSIS_READY AS coh
LEFT JOIN SAILW1169V.VB_ALL_UTI_COMB AS uti
ON coh.ALF = uti.ALF_PE
AND coh.RUTI_DIAGDATE = uti.EVENT_STR_DT);

-- generate long table of acute uti dates contributing to rUTI diagnosis

CALL FNC.DROP_IF_EXISTS('SAILW1169V.VB_ACUTE_UTI_IN_RUTI_LONG');

CREATE TABLE SAILW1169V.VB_ACUTE_UTI_IN_RUTI_LONG
AS
(SELECT jn.ALF_PE,jn.EVENT_DT
FROM SAILW1169V.UTI_JOURNEY AS jn)
WITH NO DATA;

INSERT INTO SAILW1169V.VB_ACUTE_UTI_IN_RUTI_LONG
(SELECT jn.ALF_PE,jn.EVENT_DT
FROM SAILW1169V.UTI_JOURNEY AS jn
RIGHT JOIN SAILW1169V.VB_ACUTE_UTI_IN_RUTI AS uti
ON jn.ALF_PE = uti.ALF
AND (jn.EVENT_DT = uti.RUTI_DIAGDATE
	OR jn.EVENT_DT = uti.PREV_EVENT_STR_DT
	OR jn.EVENT_DT = uti.PREV2_EVENT_STR_DT)
AND jn.UTI = 1);

------------------------------------------------------------------------------------------------

-- identify WRRS results within 7 days of acute uti contributing to rUTI diagnosis date

--Identify the earliest out of the gp, antibiotic and wrrs dates within 7 day window

CALL FNC.DROP_IF_EXISTS('SAILW1169V.COHORT2_TABLE2_7DAY');

CREATE TABLE SAILW1169V.COHORT2_TABLE2_7DAY AS
(SELECT * FROM SAILW1169V.WRRS_FINAL)
WITH NO DATA;

INSERT INTO SAILW1169V.COHORT2_TABLE2_7DAY	
SELECT wrrs.*
	FROM SAILW1169V.WRRS_FINAL AS wrrs
	INNER JOIN SAILW1169V.VB_ACUTE_UTI_IN_RUTI_LONG AS uti
		ON wrrs.ALF = uti.ALF_PE
			WHERE uti.EVENT_DT BETWEEN wrrs.URINE_DATE - 6 DAYS AND wrrs.URINE_DATE + 6 DAYS;
		
SELECT COUNT(*) FROM 
(SELECT DISTINCT ALF,
URINE_DATE,
URINE_RESULT,
URINE_ORG,
TRIMETH,
NITRO,
AMOX,
CO_AMOX,
CEFALEXIN,
GENT,
PIVMEC,
FOSFO,
CIPRO,
ESCO,
PROV_DEPT_SITEID 
FROM SAILW1169V.COHORT2_TABLE1_12MONTHS);

SELECT COUNT(*) FROM 
(SELECT DISTINCT ALF,
URINE_DATE,
URINE_RESULT,
URINE_ORG,
TRIMETH,
NITRO,
AMOX,
CO_AMOX,
CEFALEXIN,
GENT,
PIVMEC,
FOSFO,
CIPRO,
ESCO
FROM SAILW1169V.COHORT2_TABLE1_12MONTHS);
